name = "OrbitPropagationLibrary"
uuid = "c20f9b96-66de-4231-bbc8-363008277063"
authors = ["Andrew Palski"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
